config/routes.rb
OauthClient::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/signout', to: 'sessions#destroy', as: 'signout'

  resources :documents do 
    member do 
      get :share
      get :create_savepoint
      get :show_savepoint
    end
  end
  root to: 'documents#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from OAuth2::Error do |exception|
    if exception.response.status == 401
      session[:user_id] = nil
      session[:access_token] = nil
      redirect_to root_url, alert: "Access token expired, try signing in again."
    end
  end

private

  def oauth_client
    # @oauth_client ||= OAuth2::Client.new(ENV['OAUTH_ID'], ENV['OAUTH_SECRET'], site: "http://127.0.0.1:3000")
    @oauth_client ||= OAuth2::Client.new(ENV['OAUTH_ID'], ENV['OAUTH_SECRET'], site: "https://draftin.com")
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth2::AccessToken.new(oauth_client, session[:access_token])
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = access_token.get("/api/v1/documents.json").parsed if access_token
  end

  def create
    access_token.post("/api/v1/documents.json", params: {document: {content: params[:content]}})
    redirect_to root_url
  end

  def show
    @document = access_token.get("/api/v1/documents/#{params[:id]}.json").parsed

    @forks = access_token.get("/api/v1/documents/#{params[:id]}/forks.json").parsed

    @savepoints = access_token.get("/api/v1/documents/#{params[:id]}/savepoints.json").parsed
  end

  def share 
    @document = access_token.post("/api/v1/documents/#{params[:id]}/share.json").parsed
    redirect_to document_path(id: params[:id])
  end

  def destroy
    @document = access_token.delete("/api/v1/documents/#{params[:id]}.json").parsed
    redirect_to root_url
  end

  def create_savepoint
    access_token.post("/api/v1/documents/#{params[:id]}/savepoints.json").parsed
    redirect_to document_path(id: params[:id])
  end

  def show_savepoint
    @savepoint = access_token.get("/api/v1/savepoints/#{params[:id]}.json").parsed
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:access_token] = auth["credentials"]["token"]
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    session[:access_token] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/documents/index.html.erb
<h1>Document List</h1>

<% if current_user %>
  <%= form_tag documents_path do %>
    <%= text_area_tag :content %>
    <%= submit_tag "Add" %>
  <% end %>

  <ul id="tasks">
  <% @documents.each do |document| %>
    <li>
      <%= link_to "Show", document_path(id: document["id"]) %> | <%= link_to "Delete", document_path(id: document["id"]), method: :delete %>

      <div>
        <%= truncate(document["content"]) %>
      </div>
    </li>
  <% end %>
  </ul>

  <p id="logged_in">
    Logged in as <strong><%= current_user.name %></strong>.
    <%= link_to "Sign Out", signout_path %>
  </p>
<% else %>
  <p><strong>Currently not signed in.</strong></p>
  <p>
    <%= link_to "Sign in through Draft", "/auth/draft" %>
  </p>
<% end %>

app/views/documents/show.html.erb
<h4>
  <%= link_to "Home", "/" %>
</h4>

<div>
  <%= @document["content"] %>
</div>


<% if @document["token"].blank? %>
  <div>
    <%= link_to "Generate Share Token", share_document_path(id: @document["id"]) %> | <%= link_to "Save New Version", create_savepoint_document_path(id: @document["id"]) %>
  </div>

<% else %>

  <div>
    Share token: <%= @document["token"] %>
  </div>


<% end %>

<div style="margin-top: 1em">

  <% if @savepoints.blank? %>
    No other versions saved.
  <% else %> 

    <div style="">
      Versions:
    </div>

    <% @savepoints.each_with_index do |savepoint, index| %>
      <div>
        <%= link_to "Version #{@savepoints.size - index}", show_savepoint_document_path(id: savepoint["id"]) %>
      </div>
    <% end %>
  <% end %>

</div>


<div style="margin-top: 1em">
  <% if @forks.blank? %>
    No collaborators yet. 
  <% else %> 

    <div>
      Collaborators:
    </div>

    <% @forks.each do |fork| %>
      <div>
        <%= link_to fork["user"]["email"], document_path(id: fork["id"]) %>
      </div>
    <% end %>
  <% end %>

</div>

app/views/documents/show_savepoint.html.erb
<h4>
  <%= link_to "Home", "/" %>
</h4>

<div>
  Showing previous version: 
</div>

<div>
  <%= @savepoint["content"] %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>